export const recipes = {
  "rice-bowl": {
    title: "Rice Bowl",
    image: "/images/rice-bowl.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: [
      "15ml soy sauce",
      "20g brown sugar",
      "80ml water",
      "1 clove garlic",
      "1 tsp cornflower",
      "mayo",
      "1/2 lemon",
      "1 tsp rice vinegar",
      "coriander",
    ],
    steps: [
      "Put you chosen starch on to cook, once done put to the side.",
      "Mix soy sauce, brown sugar, water in a pot and bring to the boil.",
      "Let simmer for 3mins, mix in crushed garlic and cornflour, stir until mixed, put to the side.",
      "Cook your chosen protein, once done, toss in sauce.",
      "Prepare vegetables, and mix with mayo (to your taste), lemon, vinegar, salt and pepper.",
      "Assemble components and sprinkle with chopped coriander.",
    ],
  },
  pasta: {
    title: "Pasta",
    image: "/images/spaghetti.jpg",
    proteins: [
      "minced chicken",
      "minced beef",
      "minced turkey",
      "plantbased mince",
    ],
    vegetables: [
      "carrot",
      "zuchinni",
      "celery",
      "mushrooms",
      "squash",
      "capsicum",
    ],
    starchs: ["spaghetti", "edamame pasta", "pasta", "gnocchi"],
    ingredients: [
      "olive oil",
      "onion",
      "dried oregano",
      "dried basil",
      "dried rosemary",
      "stock",
      "canned tomatos",
      "garlic",
    ],
    steps: [
      "Brown onion in oil.",
      "Add your protein and cook through.",
      "Add herbs, and stock ",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
  "butter-chicken": {
    title: "Butter Chicken",
    image: "/images/butter-chicken.jpg",
    proteins: [
      "chicken",
      "meat-free chicken bites",
      "paneer",
      "tofu",
      "chickpeas",
    ],
    vegetables: ["potato", "onion", "tomato", "green beans", "mushrooms"],
    starchs: [
      "basmati",
      "brown rice",
      "bulgar wheat",
      "jasmine rice",
      "quinoa",
    ],
    ingredients: [
      "cardamom pods",
      "coconut cream",
      "corriander",
      "curry powder",
      "garlic cloves",
      "ginger",
      "paprika",
      "soya cream",
      "tomato paste",
      "vegetable stock",
    ],
    steps: [
      "Cook the starch",
      "Peel and finely chop garlic and ginger",
      "Chop your vegetables",
      "Soften onion and tomato in a pan if you're using them",
      "Add garlic, ginger, curry powder and paprika to the pan",
      "Add your remaning vegetables after a few minutes",
      "Dissolve coconut cream, tomato paste and vegetable stock in some boiled water",
      "Add stock and soya cream to the pan. This is your sauce.",
      "Fry protein an another pan and when ready, add to the sauce",
      "Serve on top of you starch of choice",
    ],
  },
  stirfry: {
    title: "Sticky Chilli Stirfry",
    image: "/images/stirfry.jpg",
    proteins: ["beef", "tofu", "pork", "meat-free mince"],
    vegetables: [
      "baby corn",
      "bamboo shoot",
      "capsicum",
      "carrot",
      "green beans",
    ],
    starchs: ["basmati", "long grain rice", "brown rice"],
    ingredients: [
      "chilli jam pot",
      "garlic",
      "ginger",
      "rice vinegar",
      "sesame oil",
      "soy sauce",
      "spring onion",
      "toasted sesame rice",
    ],
    steps: [
      "Cook your rice",
      "Cook your protein with some cooking oil in a large pan",
      "While the protein is cooking, cut up your vegetables",
      "When your protein is browned, add the vegetables to the pan",
      "Make your sticky chili sauce by mixing the following in a small bowl - the rice vinegar, soy sauce, sesame oil and chili jam bowl",
      "Once the vegetables are almost cooked, add ginger and garlic and cook until fragrant",
      "Add the sticky chili sauce and cook until everything is coated and sticky",
      "Serve with sesame seeds and sliced spring onion over your starch of choice",
    ],
  },
  tandoori: {
    title: "Tandoori Salad",
    image: "/images/tandoori-salad.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "peas", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: ["soy sauce", "coriander", "brown sugar", "garlic"],
    steps: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      "Ut non metus nec dolor vestibulum commodo",
      "Ut commodo tellus non fringilla malesuada",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
  burger: {
    title: "Burger",
    image: "/images/burger.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "peas", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: ["soy sauce", "coriander", "brown sugar", "garlic"],
    steps: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      "Ut non metus nec dolor vestibulum commodo",
      "Ut commodo tellus non fringilla malesuada",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
};
