export const recipes = {
  "rice-bowl": {
    title: "Rice Bowl",
    image: "/images/rice-bowl.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: [
      "15ml soy sauce",
      "20g brown sugar",
      "80ml water",
      "1 clove garlic",
      "1 tsp cornflower",
      "mayo",
      "1/2 lemon",
      "1 tsp rice vinegar",
      "coriander",
    ],
    steps: [
      "Put you chosen starch on to cook, once done put to the side.",
      "Mix soy sauce, brown sugar, water in a pot and bring to the boil.",
      "Let simmer for 3mins, mix in crushed garlic and cornflour, stir until mixed, put to the side.",
      "Cook your chosen protein, once done, toss in sauce.",
      "Prepare vegetables, and mix with mayo (to your taste), lemon, vinegar, salt and pepper.",
      "Assemble components and sprinkle with chopped coriander.",
    ],
  },
  pasta: {
    title: "Pasta",
    image: "/images/spaghetti.jpg",
    proteins: [
      "minced chicken",
      "minced beef",
      "minced turkey",
      "plantbased mince",
    ],
    vegetables: [
      "carrot",
      "zuchinni",
      "celery",
      "mushrooms",
      "squash",
      "capsicum",
    ],
    starchs: ["spaghetti", "edamame pasta", "pasta", "gnocchi"],
    ingredients: [
      "olive oil",
      "onion",
      "dried oregano",
      "dried basil",
      "dried rosemary",
      "stock",
      "canned tomatos",
      "garlic",
    ],
    steps: [
      "Brown onion in oil.",
      "Add your protein and cook through.",
      "Add herbs, and stock ",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
  "butter-chicken": {
    title: "Butter Chicken",
    image: "/images/butter-chicken.jpg",
    proteins: [
      "chicken",
      "meat-free chicken bites",
      "paneer",
      "tofu",
      "chickpeas",
    ],
    vegetables: ["potato", "onion", "tomato", "green beans", "mushrooms"],
    starchs: [
      "basmati",
      "brown rice",
      "bulgar wheat",
      "jasmine rice",
      "quinoa",
    ],
    ingredients: [
      "cardamom pods",
      "coconut cream",
      "corriander",
      "curry powder",
      "garlic cloves",
      "ginger",
      "paprika",
      "soya cream",
      "tomato paste",
      "vegetable stock",
    ],
    steps: [
      "Cook the starch",
      "Prepare garlic and spices",
      "Chop your vegetables",
    ],
  },
  stirfry: {
    title: "Sticky Chilli Stirfry",
    image: "/images/stirfry.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "peas", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: ["soy sauce", "coriander", "brown sugar", "garlic"],
    steps: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      "Ut non metus nec dolor vestibulum commodo",
      "Ut commodo tellus non fringilla malesuada",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
  tandoori: {
    title: "Tandoori Salad",
    image: "/images/tandoori-salad.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "peas", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: ["soy sauce", "coriander", "brown sugar", "garlic"],
    steps: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      "Ut non metus nec dolor vestibulum commodo",
      "Ut commodo tellus non fringilla malesuada",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
  burger: {
    title: "Burger",
    image: "/images/burger.jpg",
    proteins: ["chicken", "beef", "tofu", "edamame"],
    vegetables: ["corn", "carrot", "peas", "cabbage", "raddish"],
    starchs: ["basmati", "sushi rice", "quinoa"],
    ingredients: ["soy sauce", "coriander", "brown sugar", "garlic"],
    steps: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      "Ut non metus nec dolor vestibulum commodo",
      "Ut commodo tellus non fringilla malesuada",
      "Nullam ac ligula a dui dapibus tincidunt sit amet eu dolor",
      "Morbi id neque eleifend, scelerisque eros ac, imperdiet neque",
      "Nullam vulputate metus vel elit congue suscipit non sit amet neque",
    ],
  },
};
